openapi: 3.0.0
info:
  title: CampusLands API
  description: API para gestionar trainers, campers y coordinadores en CampusLands.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

paths:
  /trainers/{id}:
    get:
      summary: Obtener datos de un trainer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Datos del trainer encontrados
        "404":
          description: Trainer no encontrado
    put:
      summary: Actualizar nombre de un trainer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Nombre actualizado correctamente
    delete:
      summary: Eliminar un trainer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Trainer eliminado
        "404":
          description: Trainer no encontrado

  /campers/{id}:
    get:
      summary: Obtener datos de un camper
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Datos del camper encontrados
        "404":
          description: Camper no encontrado
    put:
      summary: Actualizar riesgo de un camper
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                riesgo:
                  type: string
                  enum: [alto, medio, bajo]
      responses:
        "200":
          description: Riesgo actualizado correctamente
    delete:
      summary: Eliminar un camper
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Camper eliminado
        "404":
          description: Camper no encontrado

  /coordinador/trainers:
    get:
      summary: Listar todos los trainers
      responses:
        "200":
          description: Lista de trainers obtenida

  /coordinador/campers:
    get:
      summary: Listar todos los campers
      responses:
        "200":
          description: Lista de campers obtenida
